columns with degenerecies
MeshToolkit/MSTK pull request #42
Opened 2016-09-29 17:58 UTC by ecoon

This expands the applicability of columnar partitioning from no degenerecies are valid to degenerate edges but not cells are valid.

It is doable now to expand this further to degenerate cells will work, but I haven't done or tested that yet.  Will do so when I can find time.  In the meantime, this has been tested.

2016-10-21 21:27 UTC, raovgarimella requested changes
I believe this will work. However, there are many moving parts in this process and even though I tried to minimize the interdependence of the various steps, I am not sure nothing will break if changed. So, apart from the minor changes, I would strongly suggest a unit test or two to test this out. 

Also, I would also request you to separate the two things being fixed here - handling of column degeneracies and minimizing the memory usage in mesh partitioning.

2016-10-21 21:27 UTC, raovgarimella commented on include/MSTK_private.h
> +  int        MESH_Partition_Some(Mesh_ptr parentmesh, int num, int *part, int begin, int end, Mesh_ptr *submeshes);
I would rename this to be MESH_Partition_Partial

2016-10-21 21:27 UTC, raovgarimella commented on src/par/MESH_Partition.c
> +              MF_Set_MasterParID(gmf,part_no+1);
I think for what is being done in this PR, the master partition ID assignment will work as is. But as we are making changes to how we do partitioning and sending we may want to move the assignment of master partition ID on global mesh entities to a global step before we start making and sending submeshes off to different processors. Not sure why I did not do this before?

2016-10-25 18:17 UTC, ecoon commented
Wait, those should not be together? Please don't take the pull request if
you see mesh partition changes. I pushed those changes after making the
pull request, thinking that they wouldn't show up in the request. They
don't work!

I'll revert back and make sure you have a pull request for just the fix
columns stuff.
On Fri, Oct 21, 2016 at 3:27 PM Rao Garimella <notifications@github.com>
wrote:

> *@raovgarimella* requested changes on this pull request.
>
> I believe this will work. However, there are many moving parts in this
> process and even though I tried to minimize the interdependence of the
> various steps, I am not sure nothing will break if changed. So, apart from
> the minor changes, I would strongly suggest a unit test or two to test this
> out.
>
> Also, I would also request you to separate the two things being fixed here
> - handling of column degeneracies and minimizing the memory usage in mesh
> partitioning.
> ------------------------------
>
> In include/MSTK_private.h
> <https://github.com/MeshToolkit/MSTK/pull/42#pullrequestreview-5317003>:
>
> > @@ -322,6 +322,7 @@ typedef enum MDelType {MDELREGION=-40, MDELFACE=-30, MDELEDGE=-20, MDELVERTEX=-1
>    int        FixColumnPartitions_UpDown(Mesh_ptr mesh, MRegion_ptr mr, MFace_ptr* up, MFace_ptr* dn);
>
>    int        MESH_Partition(Mesh_ptr parentmesh, int num, int *part, Mesh_ptr *submeshes);
> +  int        MESH_Partition_Some(Mesh_ptr parentmesh, int num, int *part, int begin, int end, Mesh_ptr *submeshes);
>
> I would rename this to be MESH_Partition_Partial
> ------------------------------
>
> In src/par/MESH_Partition.c
> <https://github.com/MeshToolkit/MSTK/pull/42#pullrequestreview-5317003>:
>
> > +            while ((lmf = List_Next_Entry(lmflist,&idx2))) {
> +              if (MF_Mesh(lmf) == submeshes[part_index]) {
> +                found_lmf = 1;
> +                break;
> +              }
> +            }
> +          }
> +
> +          if (!found_lmf) {
> +            lmf = MF_New(submeshes[part_index]);
> +            MF_Set_GEntID(lmf,MF_GEntID(gmf));
> +            MF_Set_GEntDim(lmf,MF_GEntDim(gmf));
> +            mpart_no = MF_MasterParID(gmf);
> +            if (mpart_no == 0) { /* not set */
> +              MF_Set_MasterParID(lmf,part_no);
> +              MF_Set_MasterParID(gmf,part_no+1);
>
> I think for what is being done in this PR, the master partition ID
> assignment will work as is. But as we are making changes to how we do
> partitioning and sending we may want to move the assignment of master
> partition ID on global mesh entities to a global step before we start
> making and sending submeshes off to different processors. Not sure why I
> did not do this before?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MeshToolkit/MSTK/pull/42#pullrequestreview-5317003>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE43-_Gk0aibUc0q5e-8n17Y5Mj-EWz9ks5q2S4ugaJpZM4KKSry>
> .
>

2017-07-19 21:03 UTC, certik commented
I think this can be closed.

2017-08-11 16:13 UTC, raovgarimella commented
These changes have been superseded by others

2017-08-11 16:13 UTC, closed without merging