Ethan's changes to handle columns with degeneracies
MeshToolkit/MSTK pull request #51
Opened 2017-03-15 18:02 UTC by ekikinzon

Pulled from Ethan's fork

2017-05-05 21:58 UTC, raovgarimella requested changes
Some minor tweaks to make. Also, is there a test that was failing with the old code and passes now with the new? It would be good to put that in

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +  printf("Read %-d regions", MESH_Num_Regions(mesh));
Can we put this within #ifdef DEBUG

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +  fid = fopen("col_counts.txt", "w");
Likewise, can we write out a file only if #ifdef DEBUG is enabled

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +
Check if you really got a topf and botf - otherwise code will crash inelegantly

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +
Move on to next region if you didn't get both

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +      if (topf2 != topf)
Maybe use "```expected_topf```" and "```topf```" and a call of ```FixColumnPartitions(mesh, curreg, &topf, &botf)```. Right now, the first reaction when we see ```if (topf2 != topf)``` is Whaaaa???

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +  num_not_touched = 0;
What if part of the mesh is columnar and the rest is not? Maybe the message should say that algorithm could not put all elements in a column - perhaps part of the mesh is not columnar?

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +int FixColumnPartitions_IsSide(Mesh_ptr mesh, MRegion_ptr mr, MFace_ptr rf) {
Rename to ```FixColumnPartitions_IsSideFace``` - just a suggestion

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +
There is some repetition of work in this routine (as there was in the previous version). If this is an issue, one can go through all faces and mark them as being "side" faces or not (using a temporary array) and then use that to zoom into the up and down faces in the FixColumnPartions_UpDown

2017-05-05 21:58 UTC, raovgarimella commented on src/par/FixColumnPartitions.c
> +int FixColumnPartitions_UpDown(Mesh_ptr mesh, MRegion_ptr mr, MFace_ptr* up, MFace_ptr* dn) {
FixColumnParitions_UpDownFaces? - just a suggestion

2017-05-08 16:03 UTC, ekikinzon commented on src/par/FixColumnPartitions.c
> +
Actually, the FixColumnPartitions_UpDown is going to throw an error if either of top or botf is NULL:

`  /* find two faces that are not sides */
  found = 0; i = 0;
  while (found < 2) {
    rf = List_Entry(rfaces,i);
    if (!FixColumnPartitions_IsSide(mesh, mr, rf)) {
      if (found < 1) *up = rf;
      else *dn = rf;
      found++;
    }
    i++;
    if (i >= nrf) 
      MSTK_Report("FixColumnPartitions","Mesh is not columnar, can't find both up and down faces.",MSTK_FATAL);
  }`

This also implies that we _have_ to get both, i.e. the function will throw an error if any part of domain can be represented as columns.

2017-05-09 23:09 UTC, raovgarimella approved these changes

2017-05-09 23:09 UTC, merged